variable "env" {}
variable "alb_type" {}
variable "internal" {}
variable "vpc_id" {}
variable "alb_sg_allow_cidr" {}
variable "subnets" {}
variable "dns_name" {}
variable "zone_id" {}
variable "protocol" {}
variable "port" {}
variable "certificate_arn" {}
variable "ssl_policy" {}
